### ISSUE TITLE
Account not found for the generated wallet

### ISSUE THREAD

**Issue by neofutur** [filidorwiese/ripple-wallet#25]
Hi, after installing and generating , I try the balance command and I get :

 error: 'actNotFound',
  error_code: 19,
  error_message: 'Account not found.',
  id: 1,
  ledger_hash:
   '95BB01E1EB2DA7D6554689F135C6CDB4331864C0D37F715003071275A08D5E81',
  ledger_index: 59500965,
  request:
   { account: 'rQsCyE5r1Z3yJgzS39SpET3hkcsSKM5URa',
     command: 'account_info',
     id: 1,
     ledger_index: 59500965 },
  status: 'error',
  type: 'response',
  validated: true })] 

so I dont feel like sending xrp to this wallet :(

also the wallet does not give me any "destination tag" and its required , how do I get that ?

**Comment by filidorwiese** [comment]
Hi! The wallet won't exist until you've put a minimum of 20 XRP on it.

Please read: https://xrpl.org/reserves.html
