### ISSUE TITLE
Can I communicate with this plugin via JSON RPC API

### ISSUE THREAD

**Issue by sunujacob** [filidorwiese/ripple-wallet#8]
This plugin helps me to interact from cli. How can i interact with it from php ? On which node does ripple daemon run when using this script ?

**Comment by filidorwiese** [comment]
This script is not running the Ripple daemon itself. Instead it relies on the public api's that Ripple offers at wss://s1.ripple.com and wss://s2.ripple.com. For PHP interactions with the Ripple servers, I would look elsewhere :)
