### ISSUE TITLE
Ripple addresses are between 25 and 35 characters in length?

### ISSUE THREAD

**Issue by ahdavis181** [filidorwiese/ripple-wallet#9]
https://github.com/filidorwiese/ripple-wallet/blob/46c37ad3e17bab989477a3004e3f621b78857b47/scripts/pay.js#L21

According to https://ripple.com/build/accounts/#address-encoding, Ripple addresses are between 25 and 35 characters in length. The RegExp in `pay.js` only allows addresses between 27 and 35 characters in length?

**Comment by filidorwiese** [comment]
You're totally right. Thanks for the heads up! I've improved Ripple address validations in version 1.1.0, which is out now at npm.
